"""status field for crust order model

Revision ID: 93c45b0b0f69
Revises: a184d34a2914
Create Date: 2022-12-21 11:14:28.200085

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93c45b0b0f69"
down_revision = "a184d34a2914"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crust_orders", sa.Column("status", sa.String(), nullable=True))
    op.add_column("crust_orders", sa.Column("error_info", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crust_orders", "error_info")
    op.drop_column("crust_orders", "status")
    # ### end Alembic commands ###
